// Code generated by "enumer -type TextEntityType -trimprefix Type -transform snake -text"; DO NOT EDIT.

package telegram

import (
	"fmt"
	"strings"
)

const _TextEntityTypeName = "plainlinktext_linkboldmentionhashtagitalicemailphonecodepre"

var _TextEntityTypeIndex = [...]uint8{0, 5, 9, 18, 22, 29, 36, 42, 47, 52, 56, 59}

const _TextEntityTypeLowerName = "plainlinktext_linkboldmentionhashtagitalicemailphonecodepre"

func (i TextEntityType) String() string {
	if i >= TextEntityType(len(_TextEntityTypeIndex)-1) {
		return fmt.Sprintf("TextEntityType(%d)", i)
	}
	return _TextEntityTypeName[_TextEntityTypeIndex[i]:_TextEntityTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _TextEntityTypeNoOp() {
	var x [1]struct{}
	_ = x[TypePlain-(0)]
	_ = x[TypeLink-(1)]
	_ = x[TypeTextLink-(2)]
	_ = x[TypeBold-(3)]
	_ = x[TypeMention-(4)]
	_ = x[TypeHashtag-(5)]
	_ = x[TypeItalic-(6)]
	_ = x[TypeEmail-(7)]
	_ = x[TypePhone-(8)]
	_ = x[TypeCode-(9)]
	_ = x[TypePre-(10)]
}

var _TextEntityTypeValues = []TextEntityType{TypePlain, TypeLink, TypeTextLink, TypeBold, TypeMention, TypeHashtag, TypeItalic, TypeEmail, TypePhone, TypeCode, TypePre}

var _TextEntityTypeNameToValueMap = map[string]TextEntityType{
	_TextEntityTypeName[0:5]:        TypePlain,
	_TextEntityTypeLowerName[0:5]:   TypePlain,
	_TextEntityTypeName[5:9]:        TypeLink,
	_TextEntityTypeLowerName[5:9]:   TypeLink,
	_TextEntityTypeName[9:18]:       TypeTextLink,
	_TextEntityTypeLowerName[9:18]:  TypeTextLink,
	_TextEntityTypeName[18:22]:      TypeBold,
	_TextEntityTypeLowerName[18:22]: TypeBold,
	_TextEntityTypeName[22:29]:      TypeMention,
	_TextEntityTypeLowerName[22:29]: TypeMention,
	_TextEntityTypeName[29:36]:      TypeHashtag,
	_TextEntityTypeLowerName[29:36]: TypeHashtag,
	_TextEntityTypeName[36:42]:      TypeItalic,
	_TextEntityTypeLowerName[36:42]: TypeItalic,
	_TextEntityTypeName[42:47]:      TypeEmail,
	_TextEntityTypeLowerName[42:47]: TypeEmail,
	_TextEntityTypeName[47:52]:      TypePhone,
	_TextEntityTypeLowerName[47:52]: TypePhone,
	_TextEntityTypeName[52:56]:      TypeCode,
	_TextEntityTypeLowerName[52:56]: TypeCode,
	_TextEntityTypeName[56:59]:      TypePre,
	_TextEntityTypeLowerName[56:59]: TypePre,
}

var _TextEntityTypeNames = []string{
	_TextEntityTypeName[0:5],
	_TextEntityTypeName[5:9],
	_TextEntityTypeName[9:18],
	_TextEntityTypeName[18:22],
	_TextEntityTypeName[22:29],
	_TextEntityTypeName[29:36],
	_TextEntityTypeName[36:42],
	_TextEntityTypeName[42:47],
	_TextEntityTypeName[47:52],
	_TextEntityTypeName[52:56],
	_TextEntityTypeName[56:59],
}

// TextEntityTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func TextEntityTypeString(s string) (TextEntityType, error) {
	if val, ok := _TextEntityTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _TextEntityTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to TextEntityType values", s)
}

// TextEntityTypeValues returns all values of the enum
func TextEntityTypeValues() []TextEntityType {
	return _TextEntityTypeValues
}

// TextEntityTypeStrings returns a slice of all String values of the enum
func TextEntityTypeStrings() []string {
	strs := make([]string, len(_TextEntityTypeNames))
	copy(strs, _TextEntityTypeNames)
	return strs
}

// IsATextEntityType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i TextEntityType) IsATextEntityType() bool {
	for _, v := range _TextEntityTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for TextEntityType
func (i TextEntityType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for TextEntityType
func (i *TextEntityType) UnmarshalText(text []byte) error {
	var err error
	*i, err = TextEntityTypeString(string(text))
	return err
}
